// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG-ku1voSzMIEex_55krUPvIdRqNtR3a8',
    appId: '1:24485866880:android:dbc4460c93b62db88c2565',
    messagingSenderId: '24485866880',
    projectId: 'fir-storage-upload-7c65d',
    storageBucket: 'fir-storage-upload-7c65d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfMADrFgBKzmIHgzM9EmLd19lOjkSkRQE',
    appId: '1:24485866880:ios:a33617860e90cfd18c2565',
    messagingSenderId: '24485866880',
    projectId: 'fir-storage-upload-7c65d',
    storageBucket: 'fir-storage-upload-7c65d.firebasestorage.app',
    iosClientId: '24485866880-matvcnhk8sdsn73iht8va7ii2tpkgj0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseStorageUpload',
  );
}
